source("Final/loadImage.R")
# source("Final/load.R")
# source("Final/shuffling.R")
# source("Final/singlePerson.R")
# source("Final/allPooled.R")
# source("Final/all-indi.R")
source("Final/loadPreProccessed.R")
source("Final/shuffling.R")
source("Final/preSingle.R")
source("Final/preAllPooled.R")
# source("Final/preAllIndi.R")
